APT {
FTPArchive {
Release {
Origin "Timbovill's repo";
Label "Timbovill's repo";
Suite stable;
Version 2.0;
Codename ios;
Architectures iphoneos-arm iphoneos-arm64;
Components main;
Description "Repo for mainly themes :3";
};
};
};